### ISSUE TITLE
Middle of triptych windows stays open, after Enter into selected file.

### ISSUE THREAD

**Issue by JoseConseco** [simonmclean/triptych.nvim#18]
![image](https://github.com/simonmclean/triptych.nvim/assets/13521338/f44f880b-6e2f-442d-a278-6f354e54c8a3)
Somehow middle buffer does not get destroyed correctly when entering into one of  directory files. 
I cannot reproduce this 100% of times though. But i happens from time to time.

**Comment by simonmclean** [comment]
Yikes, okay 😬 A few things that will help me debug this

- Next time it happens could you check if there are any errors in `:messages`? 
- Please post your triptych config
- Although you haven't been able to consistently reproduce it, are there are situations you've found where it's most likely to occur?

**Comment by JoseConseco** [comment]
Ok, I can recreate it actually 100% of time now. I use  "echasnovski/mini.nvim"  -  where one of functions is to emulate starter screen:
![image](https://github.com/simonmclean/triptych.nvim/assets/13521338/4d048002-2ccb-4e75-9dc9-42b08a728978)


If I fire  triptych while being in that starter screen, and enter into file I get floating window remaning (center one) from triptych:

https://github.com/simonmclean/triptych.nvim/assets/13521338/33f0c47c-96f0-475b-be5b-d961ce57f221


There are no any errors in messages.  I think it happened before debounce too. 
I do not have any config set for triptych. 
I can only tell that this starter  buffer is not editable.  And I think, I saw, for split second, : 
 - content of opened buffer being loaded into center column of  triptych,  
 - then side buffers are removed,
 - finally selected file content is loaded in background buffer, and  triptych center buffer content is cleared - but it stays visible.

**Comment by simonmclean** [comment]
Okay, I can reproduce it too having installed `mini.starter`. Interestingly it seems to happen even if you don't open a file, but just close tryptic with `q`

**Comment by simonmclean** [comment]
@JoseConseco I think it's fixed. Let me know how it goes

**Comment by JoseConseco** [comment]
Thanks. It works now. Closing the isusee
