### ISSUE TITLE
Reload window on cwd change?

### ISSUE THREAD

**Issue by mikebcbc** [simonmclean/triptych.nvim#42]
**Describe the problem you're having**
Currently, i'm using an extension mapping to trigger a cd into the dir i'm hovering over. This works great, but I have to close and reopen the triptych window to show the updated `<cwd>` at the top of the window. Is there a way to trigger a refresh of the triptych buffer that i'm missing?

**Additional context**
```
        extension_mappings = {
          ['<c-r>'] = {
            mode = 'n',
            fn = function(target)
              vim.cmd('cd ' .. target.dirname)
            end,
          },
        },
```

**Comment by simonmclean** [comment]
I think this would be a good feature to have as a first class key mapping. Might have time to implement it this weekend

**Comment by simonmclean** [comment]
@mikebcbc This has now been implemented
