### ISSUE TITLE
Put cursor on line with current file opened in buffer

### ISSUE THREAD

**Issue by tex** [simonmclean/triptych.nvim#46]
Hello,

very nice plugin! Really COOL!

When I open Triptych from a buffer that has some existing file opened, I would like cursor in Triptych to be placed on the file in the list of files.

**Comment by simonmclean** [comment]
Hi @tex This should actually be the existing functionality. Can you confirm that you're on the latest version, up to date with `main`, and then provide me your Triptych config, and either steps to reproduce or a repo where the problem is occurring?

**Comment by tex** [comment]
Hi @simonmclean. I am a litle bit embarrased. I tried it again today and it indeed works as expected. I really do not know what I did differently.

**Comment by tex** [comment]
Oh, I found where it doesn't work. I have 2 setups using same neovim config, on Linux and on Windows/WSL2. It does not work on Windows/WSL2.

**Comment by tex** [comment]
It gets path correctly, but it doesn't place cursor on correct file. Always on first one.

**Comment by simonmclean** [comment]
@tex Mind updating and trying now?

**Comment by tex** [comment]
@simonmclean Thank you! This fixed the issue.
