### ISSUE TITLE
triptych seems to lock up nvim when opening a directory containing a named pipe

### ISSUE THREAD

**Issue by Northcode** [simonmclean/triptych.nvim#58]
**Bug description**
Opening (either in the middle or the preview pane) a directory containing a named pipe locks up neovim, does not respond to `<ESC>` or `<C-c>` needed to `pkill nvim`
Noticed the issue while randomly browsing my home directory, so its pretty annoying having the whole editor suddenly lock up if you accidentally scroll past the wrong directory.

**Steps to reproduce**
1. Create a directory containing a named pipe:
```
mkdir namedpipetest
mkfifo namedpipetest/test.pipe
```
2. Browse to the directory with triptych
3. Observe lockup

I tried checking the logs for nvim and they just abruptly end when opening Triptych:
```
chdir(namedpipetest)
Executing DirChanged Autocommands for "*"
autocommand <Lua 140: ~/.local/s
```

**Setup**
- Operating system: Arch Linux
- Nvim version: 0.10.1
- Triptych config:

```lua
	{
		"simonmclean/triptych.nvim",
		event = "VeryLazy",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-tree/nvim-web-devicons",
		},
		config = function(self, opts)
			require("triptych").setup({})
			vim.keymap.set("n", "<leader>e", ":Triptych<CR>", { silent = true })
		end,
	},
```

**Comment by Northcode** [comment]
On further investigation it looks like its due to opening the file, as neovim also locks up when trying to open the file manually with `:e test.pipe`
Maybe the easiest fix would just be to make triptych skip loading previews or trying to open any named pipe?

**Comment by simonmclean** [comment]
I've pushed a fix should stop things freezing when scanning over FIFOs in Triptych

It will still crash if you try to open the file, but this is a neovim issue rather than a Triptych one. I could prevent the user from opening the file from Triptych, but my thinking is this isn't the right call. Neovim might be updated in future to handle these filetypes. What do you think?

**Comment by Northcode** [comment]
Fantastic, thanks for the speedy fix!

Yes I'm unsure if triptych should have to add extra things to work around neovim bugs, I'm fairly new to neovim so I don't know how quickly that bug would be resolved in neovim. 
One the other hand telling the user that opening pipes will lock up neovim and they should not do it seems good UX wise, even if it would only affect opening files through triptych. 

Looks like theres already an open issue about it in neovim: https://github.com/neovim/neovim/issues/29867

This fix should be good enough for me. I guess you can decide if you want to add a warning or something before attempting to open named pipes, and then it can be removed when neovim fixes the lockup-issue.
